timeout: 1800s
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/[PROJECT_ID]/[IMAGE_NAME]:latest || exit 0']

  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/[PROJECT_ID]/[IMAGE_NAME]:${TAG_NAME}", "-t", "gcr.io/[PROJECT_ID]/[IMAGE_NAME]:latest", "--cache-from=gcr.io/[PROJECT_ID]/[IMAGE_NAME]:latest", "."]

  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/[PROJECT_ID]/[IMAGE_NAME]:${TAG_NAME}"]

  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/[PROJECT_ID]/[IMAGE_NAME]:latest"]

images: ["gcr.io/$PROJECT_ID/microservice-logging:latest", "gcr.io/$PROJECT_ID/microservice-logging:${TAG_NAME}"]
